name: Deploy to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          cat << EOF > .env
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          PUSHOVER_USER=${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN=${{ secrets.PUSHOVER_TOKEN }}
          HF_TOKEN=${{ secrets.HF_TOKEN }}
          EOF

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub
          huggingface-cli login --token "$HF_TOKEN"
          huggingface-cli repo create AlexBrod/career_conversation --type=space --yes || true
          huggingface-cli repo upload AlexBrod/career_conversation . --repo-type space --yes
