name: Deploy to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          uv sync

      - name: Clone Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://AlexBrod:${HF_TOKEN}@huggingface.co/spaces/AlexBrod/career_conversation space

      - name: Overwrite Space contents with GitHub repo
        run: |
          rm -rf space/*
          rsync -av --exclude=.git ./ space/

      - name: Commit and push to Hugging Face Space
        run: |
          cd space
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Deploy from GitHub repo" || echo "Nothing to commit"
          git push
